on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo build

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - run: echo test

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
    - run: echo deploy


        