on: 
  push:

jobs:
  secret-job:
    runs-on: 
      - ubuntu-latest
    steps:
      - name: Accessing Secret
        id: step2
        run: |
          echo ${{vars.url}}
          echo $vars.url
          echo vars.url