on: 
  push:

env:
  DAY_OF_WEEK: Monday

jobs:
  windows-job:
    runs-on: 
      - macos-latest
      - windows-latest
      - ubuntu-latest
    steps:
      - name: Run ONLY on Windows
        if: ${{ runner.os == 'Windows' || env.DAY_OF_WEEK == 'Monday' }}
        run: echo "The operating system on the runner is $env:RUNNER_OS."