on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo build

  test:
    runs-on: ubuntu-latest
    steps:
    - run: exit 1

  reports:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    steps:
    - run: echo reports

        
