on: 
  push:

env:
  DAY_OF_WEEK: Friday

jobs:
  windows-job:
    runs-on: 
      - ubuntu-latest
    steps:
      - name: Run ONLY on Windows
        run: |
          echo ${{ env.DAY_OF_WEEK}}
          echo $DAY_OF_WEEK