on: 
  push:

jobs:
  windows-job:
    runs-on: 
      - ubuntu-latest
    steps:
      - name: Step 1 - set output
        id: step1
        run: |
          echo ${{secrets.test12}}

      - name: Step 2 - print output value
        id: step2
        env:
          repo_secret: secrets.test12 
        if: env.repo_secret != ''
        run: |
          echo ${{secrets.test12}}