name: wow wowo wowow

on:
  push:
    branches:
      - '!feature/**-beta'
    
jobs:
  deploy:
    environment: 
      name: development
    name: Kubernetes Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4