on: 
  push:

env:
  DAY_OF_WEEK: Friday

jobs:
  windows-job:
    runs-on: 
      - windows-latest
    steps:
      - name: Run ONLY on Windows
        if: ${{ runner.os == 'windows-latest' }}
        run: echo "The operating system is $env:RUNNER_OS."