on: 
  push:

jobs:
  secret-job:
    runs-on: 
      - ubuntu-latest
    steps:
      - name: Accessing Secret
        id: step2
        run: |
          echo "Secret vaule is - ${{env.GITHUB_ACTOR}}"
          ${{env.github.actor}}