on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Provide a custom message'
        required: true
        default: 'Hello World'
        type: string

jobs:
  print-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print the message input
        run: ${{ inputs.message }}

      - run: $input.message