name: example-workflow
on: 
  push:

jobs:
  deploy:
    # if: github.repository == 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

